.github: add pull request template and contributing guide
zz-jason/tidb-dev-guide pull request #8
Opened 2021-05-20 06:01 UTC by zz-jason

This pull request adds two files for:

- pull request template, to help contributors summarize their contributions.
- contributing guide, to help contributors getting started with how to contribute to this repo.

2021-05-20 06:23 UTC, tisonkun commented on .github/pull_request_template.md
> +
```suggestion

<!-- This repo turns on "Require signed commits" option. See also [this page](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification) to understand how to satisfy the requirement. -->

```

2021-05-20 06:23 UTC, tisonkun commented on CONTRIBUTING.md
> +
```suggestion

**Note**: This repo turns on "Require signed commits" option. See also [this page](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification) to understand how to satisfy the requirement.

```

2021-05-20 06:25 UTC, tisonkun requested changes
I'd prefer highlight we turn on "Require signed commits" since not every GitHub user aware of it.

2021-05-20 09:18 UTC, tisonkun approved these changes

2021-05-21 01:39 UTC, merged

2021-05-21 01:40 UTC, zz-jason commented
@all-contributors please add @zz-jason for content